import type { AppLocale } from "../../../app/providers/LocaleProvider";

const copies = {
  vi: {
    back: "Quay lại",
    signIn: "Đăng nhập",
    signInDescription: "Chào mừng bạn trở lại. Tiếp tục với những cuộc trò chuyện và khoảnh khắc của bạn.",
    usernameOrEmail: "Email hoặc tên đăng nhập",
    usernamePlaceholder: "Nhập email hoặc tên đăng nhập",
    password: "Mật khẩu",
    passwordPlaceholder: "Nhập mật khẩu",
    showPassword: "Hiện mật khẩu",
    hidePassword: "Ẩn mật khẩu",
    signingIn: "Đang đăng nhập",
    forgotPassword: "Quên mật khẩu?",
    or: "hoặc",
    noAccount: "Chưa có tài khoản?",
    createAccount: "Đăng ký",
    registerTitle: "Tạo tài khoản",
    registerDescription: "Xây dựng không gian của riêng bạn và bắt đầu kết nối theo cách chân thật hơn.",
    fullName: "Họ và tên",
    email: "Email",
    phoneNumber: "Số điện thoại",
    username: "Tên đăng nhập",
    confirmPassword: "Xác nhận mật khẩu",
    dateOfBirth: "Ngày sinh",
    gender: "Giới tính",
    livingIn: "Đang sống tại",
    hometown: "Quê quán",
    hobbies: "Sở thích",
    hobbiesPlaceholder: "Âm nhạc, du lịch, nhiếp ảnh",
    role: "Vai trò",
    other: "Khác",
    male: "Nam",
    female: "Nữ",
    creatingAccount: "Đang gửi mã",
    createAccountCta: "Tạo tài khoản",
    alreadyAccount: "Đã có tài khoản?",
    verifyAccount: "Xác minh tài khoản",
    verifyAccountDescription: "Chúng tôi đã gửi mã xác minh đến",
    verifyReset: "Nhập mã xác minh",
    verifyResetDescription: "Mã xác minh đặt lại mật khẩu đã được gửi đến",
    verificationCode: "Mã xác minh",
    verify: "Xác minh",
    verifying: "Đang xác minh",
    resend: "Gửi lại mã",
    resending: "Đang gửi lại",
    resendAfter: "Có thể gửi lại mã sau",
    changeEmail: "Đổi email",
    backToRegistration: "Quay lại đăng ký",
    forgotTitle: "Quên mật khẩu",
    forgotDescription: "Nhập email được liên kết với tài khoản của bạn. Chúng tôi sẽ gửi mã xác minh để đặt lại mật khẩu.",
    continue: "Tiếp tục",
    sending: "Đang gửi",
    backToSignIn: "Quay lại đăng nhập",
    resetSuccessTitle: "Kiểm tra email của bạn",
    resetSuccessText: "Mật khẩu mới đã được gửi đến email của bạn.",
    resetSuccessHint: "Dùng mật khẩu trong email để đăng nhập, sau đó bạn có thể cập nhật lại trong phần cài đặt.",
    required: "Vui lòng hoàn thành trường này.",
    passwordMismatch: "Mật khẩu xác nhận không khớp.",
  },
  en: {
    back: "Back",
    signIn: "Sign in",
    signInDescription: "Welcome back. Continue with the conversations and moments that are yours.",
    usernameOrEmail: "Email or username",
    usernamePlaceholder: "Enter your email or username",
    password: "Password",
    passwordPlaceholder: "Enter your password",
    showPassword: "Show password",
    hidePassword: "Hide password",
    signingIn: "Signing in",
    forgotPassword: "Forgot password?",
    or: "or",
    noAccount: "Don't have an account?",
    createAccount: "Register",
    registerTitle: "Create account",
    registerDescription: "Build your own space and start connecting in a more genuine way.",
    fullName: "Full name",
    email: "Email",
    phoneNumber: "Phone number",
    username: "Username",
    confirmPassword: "Confirm password",
    dateOfBirth: "Date of birth",
    gender: "Gender",
    livingIn: "Living in",
    hometown: "Hometown",
    hobbies: "Hobbies",
    hobbiesPlaceholder: "Music, travel, photography",
    role: "Role",
    other: "Other",
    male: "Male",
    female: "Female",
    creatingAccount: "Sending code",
    createAccountCta: "Create account",
    alreadyAccount: "Already have an account?",
    verifyAccount: "Verify your account",
    verifyAccountDescription: "We sent a verification code to",
    verifyReset: "Enter verification code",
    verifyResetDescription: "A password-reset code was sent to",
    verificationCode: "Verification code",
    verify: "Verify",
    verifying: "Verifying",
    resend: "Resend code",
    resending: "Resending",
    resendAfter: "You can resend the code in",
    changeEmail: "Change email",
    backToRegistration: "Back to registration",
    forgotTitle: "Forgot password",
    forgotDescription: "Enter the email linked to your account. We will send a verification code to reset your password.",
    continue: "Continue",
    sending: "Sending",
    backToSignIn: "Back to sign in",
    resetSuccessTitle: "Check your email",
    resetSuccessText: "A new password has been sent to your email.",
    resetSuccessHint: "Use the password in the email to sign in, then update it from settings if needed.",
    required: "Please complete this field.",
    passwordMismatch: "The passwords do not match.",
  },
} as const;

export function authCopy(locale: AppLocale) {
  return copies[locale];
}
